services:
    bb3mobi.seoimg.listener:
        class: bb3mobi\seoimg\event\listener
        arguments:
            - @user
            - @auth
            - @dbal.conn
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
    bb3mobi.seoimg.images:
        class: bb3mobi\seoimg\controller\images
        arguments:
            - @user
            - @auth
            - @config
            - @cache.driver
            - @dbal.conn
            - %core.root_path%
            - %core.php_ext%
